import { Id } from './id';

export enum Events {
  DRAGSTART='DRAGSTART',
  DRAG='DRAG',
  DRAGEND='DRAGEND',
  CLICK='CLICK',
  CONTEXTMENU='CONTEXTMENU',
  WHEEL='WHEEL',
  MOUSE_OUTSIDE='MOUSE_OUTSIDE',
  MOUSE_MAIN_OUTSIDE='MOUSE_MAIN_OUTSIDE',
  CONTAINER_SIZE_CHANGE='CONTAINER_SIZE_CHANGE',
  LAYOUT_MAIN_SIZE_CHANGE='LAYOUT_MAIN_SIZE_CHANGE',
  VISIBLE_AREA_CHANGE='VISIBLE_AREA_CHANGE',

  DRAGGABLE_CHANGE='DRAGGABLE_CHANGE',
  SELECTABLE_CHANGE='SELECTABLE_CHANGE',
  CHECKABLE_CHANGE='CHECKABLE_CHANGE',

  SCROLL_CHANGE='SCROLL_CHANGE',
  AUTO_SCROLL_CHANGE='AUTO_SCROLL_CHANGE',

  LAYOUT_CHANGE='LAYOUT_CHANGE',

  DATE_GRID_CHANGE='DATE_GRID_CHANGE',

  WORK_TIME_GRID_CHANGE='WORK_TIME_GRID_CHANGE',

  GROUP_CHANGE='GROUP_CHANGE',

  BAR_CHANGE='BAR_CHANGE',
  BAR_CHANGE_FRAGMENTATION='BAR_CHANGE_FRAGMENTATION',
  BAR_DRAGGING='BAR_DRAGGING',
  BAR_DRAGGING_CHANGE='BAR_DRAGGING_CHANGE',
  BAR_SELECT_CHANGE='BAR_SELECT_CHANGE',
  BAR_POS_CHANGE='BAR_POS_CHANGE',
  BAR_CONTEXTMENU='BAR_CONTEXTMENU'
}

export interface EventsInterface {
  [Events.BAR_CHANGE]:(ids: Id[])=>void
}