export enum Events {
  DRAGSTART='DRAGSTART',
  DRAG='DRAG',
  DRAGEND='DRAGEND',
  CLICK='CLICK',
  WHEEL='WHEEL',
  MOUSE_OUTSIDE='MOUSE_OUTSIDE',
  CONTAINER_SIZE_CHANGE='CONTAINER_SIZE_CHANGE',
  LAYOUT_MAIN_SIZE_CHANGE='LAYOUT_MAIN_SIZE_CHANGE',
  VISIBLE_AREA_CHANGE='VISIBLE_AREA_CHANGE',

  DRAGGABLE_CHANGE='DRAGGABLE_CHANGE',
  SELECTABLE_CHANGE='SELECTABLE_CHANGE',
  CHECKABLE_CHANGE='CHECKABLE_CHANGE',

  BAR_CHANGE='BAR_CHANGE',
  BAR_DRAGGING='BAR_DRAGGING',
  BAR_DRAGGING_CHANGE='BAR_DRAGGING_CHANGE',
  BAR_SELECT_CHANGE='BAR_SELECT_CHANGE'
}